### ISSUE TITLE
Failed to concurrency_book.generate.load()

### ISSUE THREAD

**Issue by black-lotus** [Apress/mysql-concurrency#1]
I found a bug and I can reproduce it, but I can't fix it since I don't have any experience in Python.

### Here are the bugs : 
- this [world.sql.zip](https://downloads.mysql.com/docs/world.sql.zip) no longer exists, replace to [world-db.zip](https://downloads.mysql.com/docs/world-db.zip)
- the downloaded file was already unzipped so I got the error like this `raise BadZipFile("File is not a zip file")`

### How to replicate : 
- enter to MySQL Shell using Python 
- execute this `concurrency_book.generate.load()`
- and last choose 4 `Choose Schema load job (# or name - empty to exit): 4`

**Comment by wisborg** [comment]
Thanks for the bug report and also for submitting a pull request. The issue has been fixed in v1.2.
